services:
  lgtm:
    image: docker.io/grafana/otel-lgtm:0.8.1@sha256:a4786717c4b29705e6464e2e82196fcb925de3c7f1970e923d8becac4ffd0c2a
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./lgtm/otel-lgtm/prometheus.yaml:/otel-lgtm/prometheus.yaml:ro
      - ./lgtm/otel-lgtm/grafana-dashboard-red-metrics-classic.json:/otel-lgtm/grafana-dashboard-red-metrics-classic.json:ro

